#if UNITY_EDITOR

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Animations;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;

public static class KatsuhiroV16QAValidator
{
    private const string ReportFolder =
        "Assets/_Game/QA";

    private const string ReportPath =
        ReportFolder + "/v16_1_QA_REPORT.txt";

    private const string TitleScenePath =
        "Assets/_Game/Scenes/Demo/TitleScreen.unity";

    private const string GameplayScenePath =
        "Assets/_Game/Scenes/Prototype/Foundry_Prototype.unity";

    private const string KenjiroPrefabPath =
        "Assets/_Game/Prefabs/Characters/Kenjiro/Kenjiro_Prototype.prefab";

    private const string DoryokuPrefabPath =
        "Assets/_Game/Prefabs/Enemies/Doryoku3/Doryoku3_Possessed.prefab";

    private const string InputPath =
        "Assets/_Game/Input/PlayerControls.asset";

    // RC1 incorrectly checked Kenjiro_Prototype.controller.
    // This is the real controller generated by KenjiroAnimatorBuilder.
    private const string AnimatorPath =
        "Assets/_Game/Animations/Kenjiro/KenjiroAnimatorController.controller";

    private const string PostProcessPath =
        "Assets/_Game/Art/PostProcess/Foundry_Atmosphere_v14.asset";

    private const string PcPipelinePath =
        "Assets/Settings/PC_RPAsset.asset";

    private const string PcRendererPath =
        "Assets/Settings/PC_Renderer.asset";

    private const string ReferenceFolder =
        "Assets/_Game/Art/Characters/ProductionReferences/v16";

    public struct ValidationResult
    {
        public int PassCount;
        public int WarningCount;
        public int BlockerCount;

        public bool CanBuild =>
            BlockerCount == 0;
    }

    [MenuItem("Tools/Katsuhiro/Run v16.1 QA Validation")]
    public static void Run()
    {
        RunPreflight(true);
    }

    [MenuItem("Tools/Katsuhiro/Run v16 QA Validation")]
    private static void RunLegacyAlias()
    {
        RunPreflight(true);
    }

    public static ValidationResult RunPreflight(
        bool selectReport
    )
    {
        EnsureFolder("Assets/_Game");
        EnsureFolder(ReportFolder);

        List<string> pass =
            new List<string>();

        List<string> warnings =
            new List<string>();

        List<string> blockers =
            new List<string>();

        ValidateCriticalAssets(
            pass,
            warnings,
            blockers
        );

        ValidateReferences(
            pass,
            warnings
        );

        ValidateInputActions(
            pass,
            warnings,
            blockers
        );

        ValidateAnimator(
            pass,
            warnings,
            blockers
        );

        ValidateKenjiroPrefab(
            pass,
            warnings,
            blockers
        );

        ValidateDoryokuPrefab(
            pass,
            warnings,
            blockers
        );

        ValidateBuildSettings(
            pass,
            warnings,
            blockers
        );

        ValidateURPAndPostProcess(
            pass,
            warnings,
            blockers
        );

        ValidateQualityPresets(
            pass,
            warnings,
            blockers
        );

        ValidateTitleScene(
            pass,
            warnings,
            blockers
        );

        ValidateGameplayScene(
            pass,
            warnings,
            blockers
        );

        ValidateFlowContracts(
            pass,
            warnings,
            blockers
        );

        WriteReport(
            pass,
            warnings,
            blockers
        );

        AssetDatabase.Refresh();

        if (selectReport)
        {
            TextAsset reportAsset =
                AssetDatabase.LoadAssetAtPath<TextAsset>(
                    ReportPath
                );

            if (reportAsset != null)
            {
                Selection.activeObject =
                    reportAsset;

                EditorGUIUtility.PingObject(
                    reportAsset
                );
            }
        }

        ValidationResult result =
            new ValidationResult
            {
                PassCount = pass.Count,
                WarningCount = warnings.Count,
                BlockerCount = blockers.Count
            };

        string message =
            "Katsuhiro v16.1 QA — PASS: " +
            result.PassCount +
            ", WARNING: " +
            result.WarningCount +
            ", BLOCKER: " +
            result.BlockerCount +
            ".";

        if (result.BlockerCount > 0)
            Debug.LogError(message);
        else if (result.WarningCount > 0)
            Debug.LogWarning(message);
        else
            Debug.Log(message);

        return result;
    }

    private static void ValidateCriticalAssets(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        CheckCriticalAsset(
            "Scène titre",
            TitleScenePath,
            pass,
            blockers
        );

        CheckCriticalAsset(
            "Scène gameplay",
            GameplayScenePath,
            pass,
            blockers
        );

        CheckCriticalAsset(
            "Prefab Kenjiro",
            KenjiroPrefabPath,
            pass,
            blockers
        );

        CheckCriticalAsset(
            "Prefab Doryoku-3",
            DoryokuPrefabPath,
            pass,
            blockers
        );

        CheckCriticalAsset(
            "Input Actions",
            InputPath,
            pass,
            blockers
        );

        CheckCriticalAsset(
            "Animator Controller",
            AnimatorPath,
            pass,
            blockers
        );

        CheckCriticalAsset(
            "Volume Profile v14",
            PostProcessPath,
            pass,
            blockers
        );

        CheckRecommendedAsset(
            "URP PC Asset",
            PcPipelinePath,
            pass,
            warnings
        );

        CheckRecommendedAsset(
            "URP PC Renderer",
            PcRendererPath,
            pass,
            warnings
        );
    }

    private static void ValidateReferences(
        List<string> pass,
        List<string> warnings
    )
    {
        string[] names =
        {
            "Kenjiro_TitleReference.png",
            "Yuki_TitleReference.png",
            "Takeda_TitleReference.png",
            "Kenjiro_ModelSheet.png",
            "Yuki_ModelSheet.png",
            "Takeda_ModelSheet.png"
        };

        int found = 0;

        for (int i = 0; i < names.Length; i++)
        {
            string path =
                ReferenceFolder + "/" + names[i];

            if (AssetDatabase.LoadAssetAtPath<Texture2D>(
                path
            ) != null)
            {
                found++;
            }
            else
            {
                warnings.Add(
                    "Référence personnage absente : " +
                    path
                );
            }
        }

        if (found == names.Length)
        {
            pass.Add(
                "6/6 références personnages disponibles."
            );
        }
    }

    private static void ValidateInputActions(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        InputActionAsset asset =
            AssetDatabase.LoadAssetAtPath<InputActionAsset>(
                InputPath
            );

        if (asset == null)
        {
            blockers.Add(
                "PlayerControls.asset ne peut pas être chargé comme InputActionAsset."
            );
            return;
        }

        InputActionMap map =
            asset.FindActionMap(
                "Player",
                false
            );

        if (map == null)
        {
            blockers.Add(
                "Action Map 'Player' absent."
            );
            return;
        }

        pass.Add(
            "Action Map 'Player' disponible."
        );

        string[] actions =
        {
            "Move",
            "Jump",
            "Attack",
            "HeavyAttack",
            "Dodge",
            "SpecialAttack",
            "Ability"
        };

        for (int i = 0; i < actions.Length; i++)
        {
            InputAction action =
                map.FindAction(
                    actions[i],
                    false
                );

            if (action == null)
            {
                blockers.Add(
                    "Input Action manquante : " +
                    actions[i]
                );
            }
            else
            {
                pass.Add(
                    "Input Action : " +
                    actions[i]
                );
            }
        }

        CheckBinding(
            map,
            "Jump",
            "<Keyboard>/space",
            true,
            pass,
            warnings,
            blockers
        );

        CheckBinding(
            map,
            "Attack",
            "<Keyboard>/j",
            true,
            pass,
            warnings,
            blockers
        );

        CheckBinding(
            map,
            "HeavyAttack",
            "<Keyboard>/i",
            true,
            pass,
            warnings,
            blockers
        );

        CheckBinding(
            map,
            "Dodge",
            "<Keyboard>/leftShift",
            true,
            pass,
            warnings,
            blockers
        );

        CheckBinding(
            map,
            "SpecialAttack",
            "<Keyboard>/l",
            true,
            pass,
            warnings,
            blockers
        );

        CheckBinding(
            map,
            "Ability",
            "<Keyboard>/k",
            true,
            pass,
            warnings,
            blockers
        );

        CheckBinding(
            map,
            "Jump",
            "<Gamepad>/buttonSouth",
            false,
            pass,
            warnings,
            blockers
        );

        CheckBinding(
            map,
            "Attack",
            "<Gamepad>/buttonWest",
            false,
            pass,
            warnings,
            blockers
        );

        CheckBinding(
            map,
            "Ability",
            "<Gamepad>/buttonNorth",
            false,
            pass,
            warnings,
            blockers
        );
    }

    private static void CheckBinding(
        InputActionMap map,
        string actionName,
        string path,
        bool critical,
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        InputAction action =
            map.FindAction(
                actionName,
                false
            );

        if (action == null)
            return;

        bool found = false;

        foreach (
            InputBinding binding
            in action.bindings
        )
        {
            if (binding.path == path)
            {
                found = true;
                break;
            }
        }

        if (found)
        {
            pass.Add(
                actionName +
                " binding : " +
                path
            );
        }
        else if (critical)
        {
            blockers.Add(
                actionName +
                " : binding critique absent " +
                path
            );
        }
        else
        {
            warnings.Add(
                actionName +
                " : binding manette absent " +
                path
            );
        }
    }

    private static void ValidateAnimator(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        AnimatorController controller =
            AssetDatabase.LoadAssetAtPath<AnimatorController>(
                AnimatorPath
            );

        if (controller == null)
        {
            blockers.Add(
                "Animator Controller réel introuvable : " +
                AnimatorPath
            );
            return;
        }

        pass.Add(
            "Animator Controller corrigé : KenjiroAnimatorController.controller."
        );

        HashSet<string> states =
            new HashSet<string>();

        for (
            int layerIndex = 0;
            layerIndex < controller.layers.Length;
            layerIndex++
        )
        {
            CollectStates(
                controller.layers[layerIndex].stateMachine,
                states
            );
        }

        string[] expectedStates =
        {
            "Idle",
            "Run",
            "Jump",
            "Fall",
            "Attack1",
            "Attack2",
            "Attack3",
            "HeavyAttack",
            "AirAttack",
            "Dodge",
            "DodgeCounter",
            "KikaiSpecial",
            "Hurt",
            "Death"
        };

        for (int i = 0; i < expectedStates.Length; i++)
        {
            if (states.Contains(
                expectedStates[i]
            ))
            {
                pass.Add(
                    "Animator state : " +
                    expectedStates[i]
                );
            }
            else
            {
                blockers.Add(
                    "Animator state manquant : " +
                    expectedStates[i]
                );
            }
        }

        HashSet<string> parameters =
            new HashSet<string>();

        foreach (
            AnimatorControllerParameter parameter
            in controller.parameters
        )
        {
            parameters.Add(
                parameter.name
            );
        }

        string[] criticalParameters =
        {
            "Speed",
            "VerticalSpeed",
            "Grounded",
            "Attack1",
            "Attack2",
            "Attack3",
            "HeavyAttack",
            "AirAttack",
            "Dodge",
            "DodgeCounter",
            "KikaiSpecial",
            "Hurt",
            "Death"
        };

        for (
            int i = 0;
            i < criticalParameters.Length;
            i++
        )
        {
            if (!parameters.Contains(
                criticalParameters[i]
            ))
            {
                blockers.Add(
                    "Animator parameter manquant : " +
                    criticalParameters[i]
                );
            }
        }

        if (controller.layers.Length == 0)
        {
            blockers.Add(
                "Animator Controller sans layer."
            );
        }
        else
        {
            pass.Add(
                "Animator possède " +
                controller.layers.Length +
                " layer(s)."
            );
        }
    }

    private static void CollectStates(
        AnimatorStateMachine stateMachine,
        HashSet<string> states
    )
    {
        if (stateMachine == null)
            return;

        ChildAnimatorState[] children =
            stateMachine.states;

        for (int i = 0; i < children.Length; i++)
        {
            if (children[i].state != null)
                states.Add(
                    children[i].state.name
                );
        }

        ChildAnimatorStateMachine[] childMachines =
            stateMachine.stateMachines;

        for (
            int i = 0;
            i < childMachines.Length;
            i++
        )
        {
            CollectStates(
                childMachines[i].stateMachine,
                states
            );
        }
    }

    private static void ValidateKenjiroPrefab(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        GameObject prefab =
            AssetDatabase.LoadAssetAtPath<GameObject>(
                KenjiroPrefabPath
            );

        if (prefab == null)
            return;

        Transform modelRoot =
            prefab.transform.Find(
                "ModelRoot"
            );

        if (modelRoot == null)
        {
            blockers.Add(
                "Kenjiro : ModelRoot introuvable."
            );
            return;
        }

        pass.Add(
            "Kenjiro : ModelRoot présent."
        );

        if (modelRoot.Find(
            "KenjiroCharacter_v16"
        ) != null)
        {
            pass.Add(
                "KenjiroCharacter_v16 intégré."
            );
        }
        else
        {
            warnings.Add(
                "KenjiroCharacter_v16 absent du prefab. " +
                "Rebuild conseillé."
            );
        }

        if (modelRoot.Find(
            "KikaiYurei_Device"
        ) != null)
        {
            pass.Add(
                "Kikai-Yūrei présent sur Kenjiro."
            );
        }
        else
        {
            blockers.Add(
                "Kikai-Yūrei absent du prefab Kenjiro."
            );
        }

        Animator animator =
            prefab.GetComponent<Animator>();

        if (animator == null)
        {
            blockers.Add(
                "Animator absent du prefab Kenjiro."
            );
        }
        else
        {
            pass.Add(
                "Animator présent sur le prefab Kenjiro."
            );
        }

        int missingScripts =
            CountMissingScripts(
                prefab
            );

        if (missingScripts > 0)
        {
            blockers.Add(
                "Prefab Kenjiro : " +
                missingScripts +
                " script(s) manquant(s)."
            );
        }
        else
        {
            pass.Add(
                "Prefab Kenjiro : aucun script manquant."
            );
        }
    }

    private static void ValidateDoryokuPrefab(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        GameObject prefab =
            AssetDatabase.LoadAssetAtPath<GameObject>(
                DoryokuPrefabPath
            );

        if (prefab == null)
            return;

        if (prefab.GetComponent<Doryoku3Enemy>() != null)
        {
            pass.Add(
                "Doryoku-3 : logique ennemie présente."
            );
        }
        else
        {
            blockers.Add(
                "Doryoku-3 : Doryoku3Enemy absent."
            );
        }

        if (prefab.GetComponent<Doryoku3VisualController>() != null)
        {
            pass.Add(
                "Doryoku-3 : contrôleur visuel présent."
            );
        }
        else
        {
            warnings.Add(
                "Doryoku-3 : Doryoku3VisualController absent."
            );
        }

        if (prefab.GetComponent<Doryoku3FXController>() != null)
        {
            pass.Add(
                "Doryoku-3 : VFX controller présent."
            );
        }
        else
        {
            warnings.Add(
                "Doryoku-3 : Doryoku3FXController absent."
            );
        }

        int missingScripts =
            CountMissingScripts(
                prefab
            );

        if (missingScripts > 0)
        {
            blockers.Add(
                "Prefab Doryoku-3 : " +
                missingScripts +
                " script(s) manquant(s)."
            );
        }
        else
        {
            pass.Add(
                "Prefab Doryoku-3 : aucun script manquant."
            );
        }
    }

    private static void ValidateBuildSettings(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        EditorBuildSettingsScene[] scenes =
            EditorBuildSettings.scenes;

        if (scenes.Length < 2)
        {
            blockers.Add(
                "Build Settings : moins de deux scènes."
            );
            return;
        }

        bool titleCorrect =
            scenes[0].enabled &&
            scenes[0].path == TitleScenePath;

        bool gameplayCorrect =
            scenes[1].enabled &&
            scenes[1].path == GameplayScenePath;

        if (titleCorrect &&
            gameplayCorrect)
        {
            pass.Add(
                "Build Settings : 0 TitleScreen -> 1 Foundry_Prototype."
            );
        }
        else
        {
            blockers.Add(
                "Build Settings : ordre ou activation incorrects."
            );
        }

        int extraEnabled = 0;

        for (int i = 2; i < scenes.Length; i++)
        {
            if (scenes[i].enabled)
                extraEnabled++;
        }

        if (extraEnabled > 0)
        {
            warnings.Add(
                "Build Settings : " +
                extraEnabled +
                " scène(s) supplémentaire(s) activée(s)."
            );
        }

        BuildTarget target =
            EditorUserBuildSettings.activeBuildTarget;

        if (target == BuildTarget.NoTarget)
        {
            blockers.Add(
                "Aucune plateforme de build active."
            );
        }
        else
        {
            pass.Add(
                "Plateforme active : " +
                target
            );
        }
    }

    private static void ValidateURPAndPostProcess(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        RenderPipelineAsset pipeline =
            GraphicsSettings.currentRenderPipeline;

        if (pipeline == null)
        {
            blockers.Add(
                "Aucun Render Pipeline actif. URP est requis."
            );
        }
        else
        {
            string typeName =
                pipeline.GetType().FullName;

            if (!string.IsNullOrEmpty(typeName) &&
                typeName.IndexOf(
                    "Universal",
                    StringComparison.OrdinalIgnoreCase
                ) >= 0)
            {
                pass.Add(
                    "URP actif : " +
                    pipeline.name
                );
            }
            else
            {
                blockers.Add(
                    "Render Pipeline actif non identifié comme URP : " +
                    pipeline.GetType().Name
                );
            }
        }

        RenderPipelineAsset pcAsset =
            AssetDatabase.LoadAssetAtPath<RenderPipelineAsset>(
                PcPipelinePath
            );

        if (pcAsset != null)
        {
            pass.Add(
                "PC_RPAsset chargé."
            );

            if (pipeline != null &&
                pipeline != pcAsset)
            {
                warnings.Add(
                    "Le pipeline actif n'est pas PC_RPAsset. " +
                    "Cela peut être normal selon le Quality Level courant."
                );
            }
        }

        VolumeProfile profile =
            AssetDatabase.LoadAssetAtPath<VolumeProfile>(
                PostProcessPath
            );

        if (profile == null)
        {
            blockers.Add(
                "Volume Profile de la fonderie introuvable."
            );
            return;
        }

        pass.Add(
            "Volume Profile Foundry_Atmosphere_v14 chargé."
        );

        HashSet<string> overrides =
            new HashSet<string>();

        for (
            int i = 0;
            i < profile.components.Count;
            i++
        )
        {
            VolumeComponent component =
                profile.components[i];

            if (component != null)
                overrides.Add(
                    component.GetType().Name
                );
        }

        string[] expected =
        {
            "Bloom",
            "ColorAdjustments",
            "Vignette",
            "Tonemapping"
        };

        for (int i = 0; i < expected.Length; i++)
        {
            if (overrides.Contains(
                expected[i]
            ))
            {
                pass.Add(
                    "Post-process : " +
                    expected[i]
                );
            }
            else
            {
                warnings.Add(
                    "Post-process override absent : " +
                    expected[i]
                );
            }
        }
    }

    private static void ValidateQualityPresets(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        string[] names =
            Enum.GetNames(
                typeof(
                    DemoQualityManager.DemoPreset
                )
            );

        HashSet<string> presets =
            new HashSet<string>(
                names
            );

        string[] expected =
        {
            "Performance",
            "Balanced",
            "Cinematic"
        };

        for (int i = 0; i < expected.Length; i++)
        {
            if (presets.Contains(
                expected[i]
            ))
            {
                pass.Add(
                    "Quality preset : " +
                    expected[i]
                );
            }
            else
            {
                blockers.Add(
                    "Quality preset manquant : " +
                    expected[i]
                );
            }
        }

        if (QualitySettings.names == null ||
            QualitySettings.names.Length == 0)
        {
            warnings.Add(
                "Unity Quality Settings ne contient aucun niveau nommé."
            );
        }
        else
        {
            pass.Add(
                "Unity Quality Settings disponibles : " +
                QualitySettings.names.Length
            );
        }
    }

    private static void ValidateTitleScene(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        if (!File.Exists(TitleScenePath))
            return;

        Scene scene;
        bool openedHere;

        if (!TryOpenSceneForValidation(
            TitleScenePath,
            out scene,
            out openedHere
        ))
        {
            blockers.Add(
                "Impossible d'ouvrir TitleScreen pour validation."
            );
            return;
        }

        try
        {
            GameObject[] roots =
                scene.GetRootGameObjects();

            int missing =
                CountMissingScripts(
                    roots
                );

            if (missing > 0)
            {
                blockers.Add(
                    "TitleScreen : " +
                    missing +
                    " script(s) manquant(s)."
                );
            }
            else
            {
                pass.Add(
                    "TitleScreen : aucun script manquant."
                );
            }

            DemoTitleScreenController controller =
                FindInRoots<DemoTitleScreenController>(
                    roots
                );

            if (controller == null)
            {
                blockers.Add(
                    "TitleScreen : DemoTitleScreenController absent."
                );
            }
            else
            {
                SerializedObject so =
                    new SerializedObject(
                        controller
                    );

                SerializedProperty gameplayScene =
                    so.FindProperty(
                        "gameplayScene"
                    );

                if (gameplayScene != null &&
                    gameplayScene.stringValue ==
                    "Foundry_Prototype")
                {
                    pass.Add(
                        "TitleScreen -> Foundry_Prototype configuré."
                    );
                }
                else
                {
                    blockers.Add(
                        "TitleScreen : gameplayScene mal configurée."
                    );
                }

                CheckSerializedReference(
                    so,
                    "kenjiroTexture",
                    "TitleScreen : Kenjiro texture",
                    true,
                    pass,
                    warnings,
                    blockers
                );

                CheckSerializedReference(
                    so,
                    "yukiTexture",
                    "TitleScreen : Yuki texture",
                    true,
                    pass,
                    warnings,
                    blockers
                );

                CheckSerializedReference(
                    so,
                    "takedaTexture",
                    "TitleScreen : Takeda texture",
                    true,
                    pass,
                    warnings,
                    blockers
                );
            }

            if (FindInRoots<DemoQualityManager>(
                roots
            ) != null)
            {
                pass.Add(
                    "TitleScreen : DemoQualityManager présent."
                );
            }
            else
            {
                blockers.Add(
                    "TitleScreen : DemoQualityManager absent."
                );
            }

            if (FindInRoots<Camera>(
                roots
            ) != null)
            {
                pass.Add(
                    "TitleScreen : caméra présente."
                );
            }
            else
            {
                blockers.Add(
                    "TitleScreen : aucune caméra."
                );
            }
        }
        finally
        {
            CloseValidationScene(
                scene,
                openedHere
            );
        }
    }

    private static void ValidateGameplayScene(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        if (!File.Exists(GameplayScenePath))
            return;

        Scene scene;
        bool openedHere;

        if (!TryOpenSceneForValidation(
            GameplayScenePath,
            out scene,
            out openedHere
        ))
        {
            blockers.Add(
                "Impossible d'ouvrir Foundry_Prototype pour validation."
            );
            return;
        }

        try
        {
            GameObject[] roots =
                scene.GetRootGameObjects();

            int missing =
                CountMissingScripts(
                    roots
                );

            if (missing > 0)
            {
                blockers.Add(
                    "Foundry_Prototype : " +
                    missing +
                    " script(s) manquant(s)."
                );
            }
            else
            {
                pass.Add(
                    "Foundry_Prototype : aucun script manquant."
                );
            }

            string[] requiredRoots =
            {
                "GAMEPLAY",
                "LEVEL",
                "CAMERA",
                "LIGHTING"
            };

            for (
                int i = 0;
                i < requiredRoots.Length;
                i++
            )
            {
                if (FindRoot(
                    roots,
                    requiredRoots[i]
                ) != null)
                {
                    pass.Add(
                        "Scene root : " +
                        requiredRoots[i]
                    );
                }
                else
                {
                    blockers.Add(
                        "Scene root manquant : " +
                        requiredRoots[i]
                    );
                }
            }

            PlayerInput playerInput =
                FindInRoots<PlayerInput>(
                    roots
                );

            PlayerMotor25D motor =
                FindInRoots<PlayerMotor25D>(
                    roots
                );

            PlayerHealth health =
                FindInRoots<PlayerHealth>(
                    roots
                );

            KenjiroCombatController combat =
                FindInRoots<KenjiroCombatController>(
                    roots
                );

            if (playerInput == null)
                blockers.Add("PlayerInput absent.");
            else
            {
                pass.Add("PlayerInput présent.");

                if (playerInput.actions == null)
                    blockers.Add("PlayerInput.actions non assigné.");
                else
                    pass.Add("PlayerInput.actions assigné.");

                if (playerInput.defaultActionMap == "Player")
                    pass.Add("PlayerInput defaultActionMap = Player.");
                else
                    blockers.Add("PlayerInput defaultActionMap incorrect.");
            }

            if (motor != null)
                pass.Add("PlayerMotor25D présent.");
            else
                blockers.Add("PlayerMotor25D absent.");

            if (health != null)
                pass.Add("PlayerHealth présent.");
            else
                blockers.Add("PlayerHealth absent.");

            if (combat != null)
                pass.Add("KenjiroCombatController présent.");
            else
                blockers.Add("KenjiroCombatController absent.");

            Animator animator =
                FindInRoots<Animator>(
                    roots
                );

            if (animator == null)
            {
                blockers.Add(
                    "Animator de Kenjiro absent en scène."
                );
            }
            else if (animator.runtimeAnimatorController == null)
            {
                blockers.Add(
                    "Animator de Kenjiro sans RuntimeAnimatorController."
                );
            }
            else
            {
                string path =
                    AssetDatabase.GetAssetPath(
                        animator.runtimeAnimatorController
                    );

                if (path == AnimatorPath)
                {
                    pass.Add(
                        "Animator de scène relié au bon controller."
                    );
                }
                else
                {
                    warnings.Add(
                        "Animator de scène utilise : " +
                        path
                    );
                }
            }

            KikaiWorldManager worldManager =
                FindInRoots<KikaiWorldManager>(
                    roots
                );

            if (worldManager != null)
                pass.Add("KikaiWorldManager présent.");
            else
                blockers.Add("KikaiWorldManager absent.");

            VerticalSliceDirector director =
                FindInRoots<VerticalSliceDirector>(
                    roots
                );

            if (director == null)
            {
                blockers.Add(
                    "VerticalSliceDirector absent."
                );
            }
            else
            {
                pass.Add(
                    "VerticalSliceDirector présent."
                );

                SerializedObject so =
                    new SerializedObject(
                        director
                    );

                string[] requiredReferences =
                {
                    "player",
                    "playerMotor",
                    "playerCombat",
                    "worldManager",
                    "firstEnemy",
                    "chaseSequence",
                    "boss"
                };

                for (
                    int i = 0;
                    i < requiredReferences.Length;
                    i++
                )
                {
                    CheckSerializedReference(
                        so,
                        requiredReferences[i],
                        "VerticalSliceDirector." +
                        requiredReferences[i],
                        true,
                        pass,
                        warnings,
                        blockers
                    );
                }
            }

            VerticalSliceCheckpoint[] checkpoints =
                FindAllInRoots<VerticalSliceCheckpoint>(
                    roots
                );

            if (checkpoints.Length == 0)
            {
                blockers.Add(
                    "Aucun VerticalSliceCheckpoint."
                );
            }
            else
            {
                pass.Add(
                    "Checkpoint(s) : " +
                    checkpoints.Length
                );
            }

            Doryoku3BossEncounter encounter =
                FindInRoots<Doryoku3BossEncounter>(
                    roots
                );

            if (encounter == null)
            {
                blockers.Add(
                    "Doryoku3BossEncounter absent."
                );
            }
            else
            {
                pass.Add(
                    "Doryoku3BossEncounter présent."
                );

                SerializedObject bossSO =
                    new SerializedObject(
                        encounter
                    );

                string[] bossReferences =
                {
                    "boss",
                    "player",
                    "playerMotor",
                    "playerCombat",
                    "bossCamera",
                    "bossHUD",
                    "leftGate",
                    "rightGate"
                };

                for (
                    int i = 0;
                    i < bossReferences.Length;
                    i++
                )
                {
                    CheckSerializedReference(
                        bossSO,
                        bossReferences[i],
                        "BossEncounter." +
                        bossReferences[i],
                        true,
                        pass,
                        warnings,
                        blockers
                    );
                }
            }

            if (FindInRoots<DemoPauseMenu>(
                roots
            ) != null)
                pass.Add("DemoPauseMenu présent.");
            else
                blockers.Add("DemoPauseMenu absent.");

            if (FindInRoots<DemoPerformanceHUD>(
                roots
            ) != null)
                pass.Add("DemoPerformanceHUD présent.");
            else
                warnings.Add("DemoPerformanceHUD absent.");

            if (FindInRoots<DemoQualityManager>(
                roots
            ) != null)
                pass.Add("DemoQualityManager présent en scène.");
            else
                warnings.Add(
                    "DemoQualityManager absent en scène. " +
                    "Le TitleScreen peut cependant le conserver via DontDestroyOnLoad."
                );

            Camera gameplayCamera =
                FindInRoots<Camera>(
                    roots
                );

            CameraFollow25D follow =
                FindInRoots<CameraFollow25D>(
                    roots
                );

            if (gameplayCamera == null)
            {
                blockers.Add(
                    "Caméra gameplay absente."
                );
            }
            else
            {
                pass.Add(
                    "Caméra gameplay présente."
                );

                if (gameplayCamera.allowHDR)
                    pass.Add("Caméra HDR activée.");
                else
                    warnings.Add("Caméra HDR désactivée.");
            }

            if (follow != null)
                pass.Add("CameraFollow25D présent.");
            else
                blockers.Add("CameraFollow25D absent.");

            Volume volume =
                FindInRoots<Volume>(
                    roots
                );

            if (volume == null)
            {
                warnings.Add(
                    "Global Volume absent en scène."
                );
            }
            else if (volume.sharedProfile == null)
            {
                warnings.Add(
                    "Global Volume sans profile."
                );
            }
            else
            {
                pass.Add(
                    "Global Volume relié à un profile."
                );
            }

            ValidateGameplayMarkers(
                pass,
                warnings,
                blockers
            );
        }
        finally
        {
            CloseValidationScene(
                scene,
                openedHere
            );
        }
    }

    private static void ValidateGameplayMarkers(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        if (!File.Exists(GameplayScenePath))
            return;

        string text =
            File.ReadAllText(
                GameplayScenePath
            );

        string[] criticalMarkers =
        {
            "CombatSystem_v7",
            "CombatPolish_v8",
            "VERTICAL_SLICE_V9",
            "FoundryTruePainted_v14",
            "DemoProduction_v15",
            "DemoReleaseCandidate_v16",
            "DemoReleaseCandidate_v16_1"
        };

        for (
            int i = 0;
            i < criticalMarkers.Length;
            i++
        )
        {
            if (text.Contains(
                criticalMarkers[i]
            ))
            {
                pass.Add(
                    "Marker : " +
                    criticalMarkers[i]
                );
            }
            else if (
                criticalMarkers[i] ==
                "DemoReleaseCandidate_v16_1"
            )
            {
                warnings.Add(
                    "Marker v16.1 absent : reconstruire Foundry_Prototype."
                );
            }
            else
            {
                blockers.Add(
                    "Marker historique absent : " +
                    criticalMarkers[i]
                );
            }
        }
    }

    private static void ValidateFlowContracts(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        string titleController =
            "Assets/_Game/Scripts/Demo/DemoTitleScreenController.cs";

        string pauseMenu =
            "Assets/_Game/Scripts/Demo/DemoPauseMenu.cs";

        string persistence =
            "Assets/_Game/Scripts/Demo/DemoCheckpointPersistence.cs";

        string checkpoint =
            "Assets/_Game/Scripts/VerticalSlice/VerticalSliceCheckpoint.cs";

        string playerHealth =
            "Assets/_Game/Scripts/Player/PlayerHealth.cs";

        string director =
            "Assets/_Game/Scripts/VerticalSlice/VerticalSliceDirector.cs";

        CheckSourceContract(
            titleController,
            new string[]
            {
                "DemoSceneLoader.Load",
                "gameplayScene",
                "DemoCheckpointPersistence.ClearCheckpoint"
            },
            "TitleScreen -> Nouvelle partie / Continuer",
            pass,
            blockers
        );

        CheckSourceContract(
            persistence,
            new string[]
            {
                "SaveCheckpoint",
                "TryGetForCurrentScene",
                "ClearCheckpoint"
            },
            "Checkpoint persistence",
            pass,
            blockers
        );

        CheckSourceContract(
            checkpoint,
            new string[]
            {
                "DemoCheckpointPersistence.SaveCheckpoint",
                "health.SetRespawnPoint"
            },
            "Checkpoint -> sauvegarde",
            pass,
            blockers
        );

        CheckSourceContract(
            playerHealth,
            new string[]
            {
                "DemoCheckpointPersistence.TryGetForCurrentScene",
                "spawnPosition"
            },
            "Continuer -> respawn",
            pass,
            blockers
        );

        CheckSourceContract(
            director,
            new string[]
            {
                "Doryoku3MiniBoss",
                "BossDefeated",
                "DemoSceneLoader.Load",
                "\"TitleScreen\""
            },
            "Boss -> fin -> retour titre",
            pass,
            blockers
        );

        CheckSourceContract(
            pauseMenu,
            new string[]
            {
                "DemoSceneLoader.Load",
                "titleScene",
                "GetActiveScene"
            },
            "Pause -> restart / titre",
            pass,
            blockers
        );

        if (blockers.Count == 0)
        {
            pass.Add(
                "Flow structurel : Title -> Game -> Checkpoint -> Boss -> End -> Title."
            );
        }
        else
        {
            warnings.Add(
                "Le flow structurel comporte au moins un blocker ; " +
                "voir la section BLOCKERS."
            );
        }
    }

    private static void CheckSourceContract(
        string path,
        string[] tokens,
        string label,
        List<string> pass,
        List<string> blockers
    )
    {
        if (!File.Exists(path))
        {
            blockers.Add(
                label +
                " : script absent " +
                path
            );
            return;
        }

        string source =
            File.ReadAllText(path);

        for (int i = 0; i < tokens.Length; i++)
        {
            if (!source.Contains(
                tokens[i]
            ))
            {
                blockers.Add(
                    label +
                    " : contrat absent '" +
                    tokens[i] +
                    "'."
                );
                return;
            }
        }

        pass.Add(
            "Flow contract : " +
            label
        );
    }

    private static bool TryOpenSceneForValidation(
        string path,
        out Scene scene,
        out bool openedHere
    )
    {
        scene =
            SceneManager.GetSceneByPath(
                path
            );

        if (scene.IsValid() &&
            scene.isLoaded)
        {
            openedHere = false;
            return true;
        }

        try
        {
            scene =
                EditorSceneManager.OpenScene(
                    path,
                    OpenSceneMode.Additive
                );

            openedHere = true;

            return
                scene.IsValid() &&
                scene.isLoaded;
        }
        catch (Exception exception)
        {
            Debug.LogException(exception);
            openedHere = false;
            return false;
        }
    }

    private static void CloseValidationScene(
        Scene scene,
        bool openedHere
    )
    {
        if (!openedHere ||
            !scene.IsValid() ||
            !scene.isLoaded)
        {
            return;
        }

        EditorSceneManager.CloseScene(
            scene,
            true
        );
    }

    private static GameObject FindRoot(
        GameObject[] roots,
        string name
    )
    {
        for (int i = 0; i < roots.Length; i++)
        {
            if (roots[i] != null &&
                roots[i].name == name)
            {
                return roots[i];
            }
        }

        return null;
    }

    private static T FindInRoots<T>(
        GameObject[] roots
    )
        where T : Component
    {
        for (int i = 0; i < roots.Length; i++)
        {
            T component =
                roots[i].GetComponentInChildren<T>(
                    true
                );

            if (component != null)
                return component;
        }

        return null;
    }

    private static T[] FindAllInRoots<T>(
        GameObject[] roots
    )
        where T : Component
    {
        List<T> list =
            new List<T>();

        for (int i = 0; i < roots.Length; i++)
        {
            T[] found =
                roots[i].GetComponentsInChildren<T>(
                    true
                );

            if (found != null &&
                found.Length > 0)
            {
                list.AddRange(found);
            }
        }

        return list.ToArray();
    }

    private static void CheckSerializedReference(
        SerializedObject serializedObject,
        string propertyName,
        string label,
        bool critical,
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        SerializedProperty property =
            serializedObject.FindProperty(
                propertyName
            );

        if (property == null)
        {
            if (critical)
                blockers.Add(
                    label +
                    " : propriété sérialisée introuvable."
                );
            else
                warnings.Add(
                    label +
                    " : propriété sérialisée introuvable."
                );

            return;
        }

        if (property.objectReferenceValue == null)
        {
            if (critical)
                blockers.Add(
                    label +
                    " : référence non assignée."
                );
            else
                warnings.Add(
                    label +
                    " : référence non assignée."
                );
        }
        else
        {
            pass.Add(
                label +
                " assigné."
            );
        }
    }

    private static int CountMissingScripts(
        GameObject root
    )
    {
        if (root == null)
            return 0;

        int count = 0;

        Transform[] transforms =
            root.GetComponentsInChildren<Transform>(
                true
            );

        for (int i = 0; i < transforms.Length; i++)
        {
            count +=
                GameObjectUtility
                    .GetMonoBehavioursWithMissingScriptCount(
                        transforms[i].gameObject
                    );
        }

        return count;
    }

    private static int CountMissingScripts(
        GameObject[] roots
    )
    {
        int count = 0;

        for (int i = 0; i < roots.Length; i++)
            count +=
                CountMissingScripts(
                    roots[i]
                );

        return count;
    }

    private static void CheckCriticalAsset(
        string label,
        string path,
        List<string> pass,
        List<string> blockers
    )
    {
        UnityEngine.Object asset =
            AssetDatabase.LoadMainAssetAtPath(
                path
            );

        if (asset != null)
        {
            pass.Add(
                label +
                " présent : " +
                path
            );
        }
        else
        {
            blockers.Add(
                label +
                " manquant : " +
                path
            );
        }
    }

    private static void CheckRecommendedAsset(
        string label,
        string path,
        List<string> pass,
        List<string> warnings
    )
    {
        UnityEngine.Object asset =
            AssetDatabase.LoadMainAssetAtPath(
                path
            );

        if (asset != null)
        {
            pass.Add(
                label +
                " présent."
            );
        }
        else
        {
            warnings.Add(
                label +
                " absent : " +
                path
            );
        }
    }

    private static void WriteReport(
        List<string> pass,
        List<string> warnings,
        List<string> blockers
    )
    {
        StringBuilder report =
            new StringBuilder();

        report.AppendLine(
            "KATSUHIRO v16.1 RC2 — QA HOTFIX + BUILD VALIDATION"
        );

        report.AppendLine(
            "=================================================="
        );

        report.AppendLine(
            "Version : " +
            DemoBuildInfo.FullLabel
        );

        report.AppendLine(
            "Unity : " +
            Application.unityVersion
        );

        report.AppendLine(
            "Build target : " +
            EditorUserBuildSettings.activeBuildTarget
        );

        report.AppendLine();

        report.AppendLine(
            "STATUS : " +
            (
                blockers.Count == 0
                    ? "READY FOR BUILD TEST"
                    : "BLOCKED"
            )
        );

        report.AppendLine(
            "PASS=" +
            pass.Count +
            " | WARNING=" +
            warnings.Count +
            " | BLOCKER=" +
            blockers.Count
        );

        report.AppendLine();
        report.AppendLine("PASS");
        report.AppendLine("----");

        if (pass.Count == 0)
            report.AppendLine("[PASS] Aucun.");
        else
        {
            for (int i = 0; i < pass.Count; i++)
                report.AppendLine(
                    "[PASS] " +
                    pass[i]
                );
        }

        report.AppendLine();
        report.AppendLine("WARNING");
        report.AppendLine("-------");

        if (warnings.Count == 0)
            report.AppendLine("[WARNING] Aucun.");
        else
        {
            for (
                int i = 0;
                i < warnings.Count;
                i++
            )
            {
                report.AppendLine(
                    "[WARNING] " +
                    warnings[i]
                );
            }
        }

        report.AppendLine();
        report.AppendLine("BLOCKER");
        report.AppendLine("-------");

        if (blockers.Count == 0)
            report.AppendLine("[BLOCKER] Aucun.");
        else
        {
            for (
                int i = 0;
                i < blockers.Count;
                i++
            )
            {
                report.AppendLine(
                    "[BLOCKER] " +
                    blockers[i]
                );
            }
        }

        report.AppendLine();
        report.AppendLine(
            "NOTE : un rapport sans blocker valide la structure " +
            "du projet pour un test de build. Il ne remplace pas " +
            "le test Play Mode, le profiling FPS ni le test de l'exécutable."
        );

        File.WriteAllText(
            ReportPath,
            report.ToString()
        );
    }

    private static void EnsureFolder(
        string path
    )
    {
        if (AssetDatabase.IsValidFolder(path))
            return;

        string parent =
            Path.GetDirectoryName(path)
                ?.Replace("\\", "/");

        string folder =
            Path.GetFileName(path);

        if (!string.IsNullOrEmpty(parent) &&
            !AssetDatabase.IsValidFolder(parent))
        {
            EnsureFolder(parent);
        }

        if (!string.IsNullOrEmpty(parent))
        {
            AssetDatabase.CreateFolder(
                parent,
                folder
            );
        }
    }
}

#endif
